<a href="https://colab.research.google.com/github/Lawal-Abdulsabur/Access-to-affordable-drinking-water-project-1/blob/main/Data_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Library
import pandas as pd

In [ ]:
# Load dataset
df= pd.read_csv("pharmacy_messy.csv")

Exploratory data analysis

In [ ]:


df.head()

,Receipt ID,BRANCH,Customer Type,Gender,Drug Category,Unit Price,Quantity,Total Amount,Date,Payment Method,Pharmacist Name,Rating
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,GHS 39.87,4,159.48,4/17/2023,Mobile Money,Ama Mensah,4.8
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,GHS 145.83,10,1458.30,"June 7, 2023",Mobile Money,NaN,8.8
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,GHS 189.64,9,1706.76,"January 9, 2023",Cash,Yaw Darko,5.2
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,GHS 106.14,4,424.56,2/23/2023,Card,Ama Mensah,5.5
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,GHS 133.76,1,133.76,6/27/2023,Cash,NaN,4.2

In [ ]:
df.tail()

,Receipt ID,BRANCH,Customer Type,Gender,Drug Category,Unit Price,Quantity,Total Amount,Date,Payment Method,Pharmacist Name,Rating
195,RX-1162-248,Takoradi,Prescription,Male,Skincare,GHS 116.61,6,699.66,6/5/2023,Insurance,Yaw Darko,3.8
196,RX-4300-561,Accra Central,Prescription,Male,Skincare,GHS 118.71,11,1305.81,5/22/2023,Insurance,Abena Owusu,5.5
197,RX-1907-743,Takoradi,Walk-in,Female,Vitamins & Supplements,GHS 41.21,2,82.42,1/14/2023,Mobile Money,Kofi Asante,9.0
198,RX-7313-719,Takoradi,Walk-in,Female,Antimalarials,GHS 102.24,2,204.48,"June 17, 2023",Mobile Money,Ama Mensah,7.9
199,RX-3248-830,Kumasi,Walk-in,Female,Painkillers,GHS 28.01,6,168.06,"April 6, 2023",Insurance,Abena Owusu,8.0

In [ ]:
df.head(10)

,Receipt ID,BRANCH,Customer Type,Gender,Drug Category,Unit Price,Quantity,Total Amount,Date,Payment Method,Pharmacist Name,Rating
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,GHS 39.87,4,159.48,4/17/2023,Mobile Money,Ama Mensah,4.8
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,GHS 145.83,10,1458.30,"June 7, 2023",Mobile Money,NaN,8.8
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,GHS 189.64,9,1706.76,"January 9, 2023",Cash,Yaw Darko,5.2
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,GHS 106.14,4,424.56,2/23/2023,Card,Ama Mensah,5.5
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,GHS 133.76,1,133.76,6/27/2023,Cash,NaN,4.2
5,RX-1907-755,Kumasi,Insurance,Male,Painkillers,GHS 65.41,1,65.41,"April 7, 2023",Card,Abena Owusu,4.0
6,RX-3464-722,Accra Central,Prescription,Female,Skincare,GHS 83.79,3,251.37,2/24/2023,Insurance,Yaw Darko,9.5
7,RX-6228-889,Kumasi,Walk-in,Male,Antibiotics,GHS 33.01,3,99.03,2/18/2023,Mobile Money,Yaw Darko,4.0
8,RX-1781-445,Kumasi,Walk-in,Female,Antibiotics,GHS 172.28,6,1033.68,1/19/2023,Mobile Money,Ama Mensah,6.5
9,RX-3969-138,Accra Central,Prescription,Female,Vitamins & Supplements,GHS 165.36,7,NaN,5/3/2023,Card,Yaw Darko,8.7

In [ ]:
df.head(8)

,Receipt ID,BRANCH,Customer Type,Gender,Drug Category,Unit Price,Quantity,Total Amount,Date,Payment Method,Pharmacist Name,Rating
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,GHS 39.87,4,159.48,4/17/2023,Mobile Money,Ama Mensah,4.8
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,GHS 145.83,10,1458.30,"June 7, 2023",Mobile Money,NaN,8.8
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,GHS 189.64,9,1706.76,"January 9, 2023",Cash,Yaw Darko,5.2
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,GHS 106.14,4,424.56,2/23/2023,Card,Ama Mensah,5.5
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,GHS 133.76,1,133.76,6/27/2023,Cash,NaN,4.2
5,RX-1907-755,Kumasi,Insurance,Male,Painkillers,GHS 65.41,1,65.41,"April 7, 2023",Card,Abena Owusu,4.0
6,RX-3464-722,Accra Central,Prescription,Female,Skincare,GHS 83.79,3,251.37,2/24/2023,Insurance,Yaw Darko,9.5
7,RX-6228-889,Kumasi,Walk-in,Male,Antibiotics,GHS 33.01,3,99.03,2/18/2023,Mobile Money,Yaw Darko,4.0

In [ ]:
print(df.columns)

Index(['Receipt ID', 'BRANCH', 'Customer Type', 'Gender', 'Drug Category',
       'Unit Price', 'Quantity', 'Total Amount', 'Date', 'Payment Method',
       'Pharmacist Name', 'Rating'],
      dtype='object')

In [ ]:
df.shape

(200, 12)

In [ ]:
print(len(df.columns))

12

Basic Data Understanding

In [ ]:
df.describe()

         Quantity  Total Amount      Rating
count  200.000000    188.000000  185.000000
mean     6.210000    609.114840    6.342703
std      3.499591    527.845615    2.143662
min      1.000000     15.060000    3.000000
25%      3.000000    182.705000    4.400000
50%      6.000000    406.480000    6.500000
75%      9.000000    930.980000    8.300000
max     12.000000   2287.680000    9.800000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Receipt ID       200 non-null    object
 1   BRANCH           200 non-null    object
 2   Customer Type    200 non-null    object
 3   Gender           200 non-null    object
 4   Drug Category    200 non-null    object
 5   Unit Price       200 non-null    object
 6   Quantity         200 non-null    int64
 7   Total Amount     188 non-null    float64
 8   Date             200 non-null    object
 9   Payment Method   200 non-null    object
 10  Pharmacist Name  190 non-null    object
 11  Rating           185 non-null    float64
dtypes: float64(2), int64(1), object(9)
memory usage: 18.9+ KB

In [ ]:
df["BRANCH"].value_counts()

BRANCH
Accra Central    84
Takoradi         61
Kumasi           55
Name: count, dtype: int64

In [ ]:
df["Customer Type"].value_counts()

Customer Type
Insurance       75
Walk-in         68
Prescription    57
Name: count, dtype: int64

In [ ]:
df["Gender"].value_counts()

Gender
Female    101
Male       99
Name: count, dtype: int64

In [ ]:
df["Drug Category"].value_counts()

Drug Category
Painkillers               41
Skincare                  37
Antimalarials             37
Vitamins & Supplements    33
Antibiotics               29
Diabetes & BP             23
Name: count, dtype: int64

In [ ]:
df["Payment Method"].value_counts()

Payment Method
Mobile Money    61
Card            52
Insurance       51
Cash            36
Name: count, dtype: int64

In [ ]:
df["Pharmacist Name"].value_counts()